### ISSUE TITLE
Get listed on FMI tools page  https://fmi-standard.org/tools/

### ISSUE THREAD

**Issue by chrbertsch** [hyumo/qFMU#19]
see https://github.com/modelica/fmi-standard.org/blob/main/CONTRIBUTING.md#updating-the-tools-list

**Comment by hyumo** [comment]
Hi @chrbertsch, validation information has been added. see https://github.com/hyumo/qFMU/tree/main/examples. Feel free to create new issues if you see other rooms for improvement. I'll focus on adding new features next.

**Comment by chrbertsch** [comment]
> Hi @chrbertsch, validation information has been added. see https://github.com/hyumo/qFMU/tree/main/examples. Feel free to create new issues if you see other rooms for improvement. I'll focus on adding new features next.

Hi @hyumo ,
thanks for adding the compatibility information! If you have successfully simulated your FMUs with more importing tools, you could also add them.
